### ISSUE TITLE
Pickup donation cancellation

### ISSUE THREAD

**Issue by francischeung** [SeattleGiveCamp/SGC2017_OSL#19]
If donation is already accepted, recipient can hit the cancel button which should relist donation and send notification to donor.

**Comment by sujithkrish** [comment]
Can you provide more details here? There are 3 use cases here - 
1. recipient accepting, and donor marking it as complete. 
2. recipient accepting, but didnt really claim it, and accordingly donor relisting the donation
3. recipient accepting, but didn't claim it within stipulated time, and accordingly donor relisting the donation

What about canceling the donation since it has expired OR would like to remove the donation from donation list?

**Comment by sjgllghr** [comment]
I did a basic implementation of the web side of this last week when I was working on the donation status api issue. I'm not saying this is how it should work but this is how it works at present.

Right now donors can only mark as completed if their donation has been accepted first, and recipients can relist regardless of status. Donors can relist as long as the donation is not marked as completed. 

In the first case you mention, I guess it would be up to the recipient to relist under the current implementation. The other two cases would be handled by donor relist. (Though there is still a problem of the donor possibly relisting while someone on the way to pick it up).

There isn't currently anything to handle relisting expired donations. Right now it would just go back to listed, since we aren't doing anything with expired listings yet. There also isn't a delete option, but I can make one if thats something we want to have available (I think originally we were worried this could be used as a way to avoid saying it was wasted). There is support for editing but not for removing entirely.

I'm not sure how much of this should be handled in the app vs. over phone, in person, etc. I was under the impression that the app was a way to facilitate donation matching, but there is still more communication that needs to happen between the two parties outside the app.
